spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/yongyong
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  header: Authorization
  token-validity-in-seconds: 86400